name: Build, test, migrate and package the ProductManager.API
on:
  push:
    branches: [feature/cicd]
  pull_request:
    branches: [feature/cicd]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services: #needed for the integration tests to run
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: YourStrong!Passw0rd
        ports:
          - 1433:1433    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release
        