# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - ProductManagerAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef

      - name: Replace connection string in app settings by connection string in github secret
        uses: microsoft/variable-substitution@v1
        with: 
          files: 'ProductManager.API/appsettings.json' 
        env: 
          ConnectionStrings.defaultConnectionString: ${{ secrets.AZURE_SQL_CONNECTIONSTRING }}
          JWT.Key: ${{ secrets.PRODUCTMANAGER_JWT_KEY }}

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Create EF Migration Bundle
        env:
          EF_MIGRATIONS_CONNECTION: "Server=design-time-fake;Database=FakeDB;User Id=fake;Password=fake;Encrypt=True;" #Will be replaced in bundle
        run: dotnet ef migrations bundle --project ProductManager.DAL/ProductManager.DAL.csproj  --startup-project ProductManager.API/ProductManager.API.csproj --output efbundle.exe
      - name: Run EF Core Migrations
        run: ./efbundle.exe --connection "${{ secrets.AZURE_SQL_CONNECTIONSTRING }}"

      - name: Test
        run: dotnet test --no-build --configuration Release
      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1B48AFA803824EF790C16801C6F49DFF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_799B2904AB7B4DB2952D44282821C09F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_57B55768210E40FC86186587D464C188 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ProductManagerAPI'
          slot-name: 'Production'
          package: .
          